name: CI Pipeline


on:
  push:

jobs:
  build-test-compose:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Health Script
        run: |
          chmod +x scripts/health.sh
          ./scripts/health.sh

      - name: Build Docker Image
        run: |
          docker build -t luka-nginx:v1

      - name: Validate Docker Compose
        run: |
          docker compose config
